#!/usr/bin/env bash

cp $HOME/.config/nvim/spell/en.utf-8.add /tmp/mydictionary.txt
aspell --lang=en create master /tmp/mydictionary.rws < /tmp/mydictionary.txt
cp /tmp/mydictionary.rws /usr/local/Cellar/aspell/0.60.8/lib/aspell-0.60
