#!/usr/bin/env bash

to_get=("to_add"
		"to_make"
		"to_learn"
		"to_write"
		"to_do")

for item in "${to_get[@]}"; do
	tmp_todos=$HOME/life/docs/ToDos/$item.tmp.md
	todos=$HOME/life/docs/ToDos/$item.md
	ag --nobreak --nonumbers --noheading --nofilename  $item $HOME/labbook > $tmp_todos
	cat $todos >> $tmp_todos
	sort $tmp_todos | uniq > $todos
	rm $tmp_todos
done

while read line;
do
	echo "$line"
  sed -i "/"$line"/d" $HOME/life/docs/ToDos/*.md 
done < $HOME/life/docs/ToDone/to_done.md
