#!/usr/bin/env bash

tail -n +1 $HOME/.aspell.en.pws >> $HOME/.config/nvim/spell/en.utf-8.add
sort $HOME/.config/nvim/spell/en.utf-8.add | uniq > $HOME/.config/nvim/spell/en.utf-8.added
head -n +1 $HOME/.aspell.en.pws > $HOME/.aspell.x.txt
grep -vE '\d' $HOME/.config/nvim/spell/en.utf-8.added >> $HOME/.aspell.x.txt 
rm $HOME/.aspell.en.pws 
mv $HOME/.aspell.x.txt $HOME/.aspell.en.pws
