#!/usr/bin/env bash

main () {
        projectname=$1
        mkdir ./$projectname
        cp $HOME/programs/bash/newprojects/pystartfile.py ./$projectname/
        cp $HOME/programs/bash/newprojects/pystarttestfile.py ./$projectname/
        mv ./$projectname/pystartfile.py ./$projectname/$projectname.py
        mv ./$projectname/pystarttestfile.py ./$projectname/test_$projectname.py
        touch ./$projectname/__init__.py
        sed -i "s/newProject/$projectname/g" ./$projectname/test_$projectname.py
        cd ./$projectname
        echo "run tests like 'python3 -m unittest discover \"test_$projectname\"'"
}


main "$@"
